# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4c2d99793588a58b2fd18e4eb500daa6"
name = "Wishlist"
application_url = "https://spread-grade-influence-maintenance.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,unauthenticated_read_customers,unauthenticated_write_customers"

[auth]
redirect_urls = [ "https://spread-grade-influence-maintenance.trycloudflare.com/api/auth" ]


[app_proxy]
# This MUST match your application_url for the proxy to find your server
url = "https://spread-grade-influence-maintenance.trycloudflare.com"
subpath = "wishlist-api"
prefix = "apps"